### ISSUE TITLE
Could intel ipp-crypto build on M1?

### ISSUE THREAD

**Issue by peiji1981** [secretflow/ppu#8]
Could the related package intel ipp-crypto build on M1?

**Comment by anakinxc** [comment]
Intel's ippcp is heavily rely on AVX/AVX2/AVX512 instruction sets, I don't think it can build or work on M1 (even through Rosetta). We are focusing on X86 platform right now, but with the ARM transition trend, things may change in the future.

**Comment by peiji1981** [comment]
thx，how about ppu docker version，it seems still need bazel build after pull the docker images？

**Comment by anakinxc** [comment]
Which docker image are you using? 
registry.hub.docker.com/secretflow/ppu-gcc11-anolis-dev:latest this one should already have bazel installed.

**Comment by peiji1981** [comment]
> Which docker image are you using? registry.hub.docker.com/secretflow/ppu-gcc11-anolis-dev:latest this one should already have bazel installed.

yes, but when building, the following problem happens


`root@097495902b9a dev]# bazel build //... -c dbg
Opening zip "/proc/self/exe": lseek(): Bad file descriptor
[FATAL 03:03:26.906 src/main/cpp/archive_utils.cc:51] Failed to open '/proc/self/exe' as a zip file: (error: 9): Bad file descriptor
ERROR: The project you're trying to build requires Bazel 4.*.* (specified in /home/admin/dev/.bazelversion), but it wasn't found in /usr/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
  (cd "/usr/bin" && curl -fLO https://releases.bazel.build/4.*.*/release/bazel-4.*.*-linux-x86_64 && chmod +x bazel-4.*.*-linux-x86_64)`

**Comment by anakinxc** [comment]
Sounds like this issue https://github.com/bazelbuild/bazel/issues/11379

Can you try workaround mentioned there: https://github.com/bazelbuild/bazel/issues/11379#issuecomment-852255679
